name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2
        with:
          feed_list: "https://santii.foo.ng/rss.xml"
          max_post_count: 3
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: "README.md"
          writeTo: "README.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with latest activity
          branch: main
          file_pattern: README.md
