name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://santii.foo.ng/"
      - uses: ethomson/repo-activity-action@v0.1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          days: 7
          max_repos: 3
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with latest activity
          branch: main
          file_pattern: README.md
